### ISSUE TITLE
Error while building

### ISSUE THREAD

**Issue by matteodellamico** [iesl/xcluster#2] opened 2018-07-26 16:18 UTC
Hi,

I'm trying to run this, and I'm following your instructions. On a machine running ubuntu 16.04, I get these errors:

[ERROR] error: scala.reflect.internal.MissingRequirementError: object java.lang.Object in compiler mirror not found.
[ERROR]  at scala.reflect.internal.MissingRequirementError$.signal(MissingRequirementError.scala:17)
[ERROR]  at scala.reflect.internal.MissingRequirementError$.notFound(MissingRequirementError.scala:18)
[ERROR] Failed to execute goal org.scala-tools:maven-scala-plugin:2.15.2:compile (default) on project xcluster: wrap: org.apache.commons.exec.ExecuteException: Process exited with an error: 1(Exit value: 1) -> [Help 1]

I don't know maven and I can't understand the error message. Can you help me?

Thanks a lot!

**Comment by sesamepaste** [comment] 2018-09-28 23:01
Stuck on the same @matteodellamico  got any ideas ?

@nmonath @akobre01  any idea how someone could port your max_distance approximation into the cosine space. I am dealing with clustering a huge set of documents

**Comment by nmonath** [comment] 2018-09-29 04:47
Hi @sesamepaste,

Could you tell us your java version? And also what your JAVA_HOME and JAVA_HOME_8 environment variables are?

On our Centos machine this is: 
```
export JAVA_HOME=/share/apps/jdk1.8.0_131
export JAVA_HOME_8=/share/apps/jdk1.8.0_131
```
I believe that these interact with maven. If you haven't already, could you try setting them and seeing if you get the same error still?

Additionally, you could also try specifying the version of java in the pom.xml by changing the properties section from: 
```
<properties>
        <scala.majorVersion>2.11</scala.majorVersion>
        <scala.minorVersion>.7</scala.minorVersion>
</properties>
```
to

```
<properties>
        <scala.majorVersion>2.11</scala.majorVersion>
        <scala.minorVersion>.7</scala.minorVersion>
    <maven.compiler.source>1.8</maven.compiler.source>
   <maven.compiler.target>1.8</maven.compiler.target>
</properties>
```

As for cosine similarities, you could unit norm your vectors so that euclidean distances are proportional to the cosine similarity between your vectors (https://stats.stackexchange.com/questions/146221/is-cosine-similarity-identical-to-l2-normalized-euclidean-distance).

**Comment by nmonath** [comment] 2018-10-10 20:39
@sesamepaste were you able to resolve this error? If so, I'd like to close this issue. Thanks!

**Comment by sesamepaste** [comment] 2018-10-11 15:39
@nmonath the link you mentioned equates cosine distance and square of euclidean distance (Emphasis on the square). Also even after modifying the code to use square of euclidean distance, I was not able to achieve high subtree purity. Similar datapoints going to different subtrees is one of the  major issues i am facing.

> As for cosine similarities, you could unit norm your vectors so that euclidean distances are proportional to the cosine similarity between your vectors (https://stats.stackexchange.com/questions/146221/is-cosine-similarity-identical-to-l2-normalized-euclidean-distance).

**Comment by nmonath** [comment] 2018-10-15 12:42
Hello @sesamepaste, could you elaborate on the results your seeing: 

> Similar datapoints going to different subtrees is one of the major issues i am facing.

Is it that points that are close in euclidean space are not ending up near by one another in the tree? 

Have you tried visualizing the trees with the [graphviz script](https://github.com/iesl/xcluster/blob/master/bin/util/graphviz_tree.sh) we provide?

**Comment by nmonath** [comment] 2019-08-13 15:23
Hi, I plan on closing this thread since it is inactive. If there are any other questions / comments about this let me know. Thank you!

**Comment by sesamepaste** [comment] 2019-08-19 07:05
Setting target as jdk8 worked

> Similar datapoints going to different subtrees is one of the major issues i am facing.


I had moved on too other methods, I'll revisit this again. Since it was not related to the original issue we can discuss it in a separate issue if the need arises.

The issue is resolved. Please close the issue

**Closed as completed** 2019-08-19 14:09 UTC
